### ISSUE TITLE
Stability of gamethrive

### ISSUE THREAD

**Issue by aigninja** [hashcube/gamethrive#1]
Is gamethrive pushnotification stable(No 'service_not_available' error while registration)? GCM push notification has several issues and we are planning for switching to stable push notification service.

**Comment by jishnu7** [comment]
We haven't faced any issue yet. 

 Onesignal (gamethrive) uses GCM apis in the backend

**Comment by aigninja** [comment]
Good to hear its working fine. If gamethrive uses GCM apis in backend then
what are benefits of using it? I mean GCM have several isssues like
registration error, in old sdk withour gtalk/hangout GCM fails. Does
gamethrive solves such issues?

What is minimum ANDROID API version needed to use this plugin?

-Ninja

**Comment by jishnu7** [comment]
Not sure about the min sdk needed for the plugin, but we were using it without an issue on android 2.3

We upgraded this plugin to v3.0.3. This repo is kept so that old versions won't break.

Please open a new issue here, https://github.com/hashcube/onesignal, if you are still facing the issue.
